import React, { useState } from "react";
import {
  Sparkles,
  ArrowLeft,
  Calendar,
  Layers,
  Star,
  CheckCircle,
  FileText,
  Clock,
  Download,
  Flame,
  Brain,
  Award,
  ChevronRight,
  BookOpen,
  Share2,
  Printer,
  ChevronDown
} from "lucide-react";
import { AISummary, MCQQuestion, Flashcard } from "../types";
import canvasConfetti from "canvas-confetti";

interface SummaryDetailProps {
  summary: AISummary;
  onBack: () => void;
  onToggleBookmark: (e: React.MouseEvent, summary: AISummary) => void;
  onDelete: (summaryId: string) => void;
}

export function SummaryDetail({
  summary,
  onBack,
  onToggleBookmark,
  onDelete,
}: SummaryDetailProps) {
  const [activeTab, setActiveTab] = useState<
    "summary" | "keypoints" | "actions" | "studynotes" | "flashcards" | "quiz" | "mindmap"
  >("summary");

  const [summaryLayout, setSummaryLayout] = useState<"short" | "detailed">("short");

  // Interaction States
  const [checkedActionItems, setCheckedActionItems] = useState<{ [key: number]: boolean }>({});
  const [clickedFlashcards, setClickedFlashcards] = useState<{ [key: number]: boolean }>({});
  
  // Quiz evaluation states
  const [quizAnswers, setQuizAnswers] = useState<{ [key: number]: number }>({});
  const [quizSubmitted, setQuizSubmitted] = useState<{ [key: number]: boolean }>({});

  const toggleActionItem = (index: number) => {
    setCheckedActionItems((prev) => ({
      ...prev,
      [index]: !prev[index],
    }));
  };

  const flipFlashcard = (index: number) => {
    setClickedFlashcards((prev) => ({
      ...prev,
      [index]: !prev[index],
    }));
  };

  const handleSelectOption = (qIndex: number, optIndex: number) => {
    if (quizSubmitted[qIndex]) return; // locked after answered
    setQuizAnswers((prev) => ({
      ...prev,
      [qIndex]: optIndex,
    }));
    setQuizSubmitted((prev) => ({
      ...prev,
      [qIndex]: true,
    }));

    // Reward when they answer correctly
    if (optIndex === summary.questions[qIndex].answerIndex) {
      canvasConfetti({
        particleCount: 80,
        spread: 60,
        origin: { y: 0.85 },
        colors: ["#c3c0ff", "#4cd7f6", "#4f46e5"],
      });
    }
  };

  // Export functions
  const handleExportTxt = () => {
    const textContent = `
=== ${summary.title.toUpperCase()} ===
Generated by SmartNote AI: ${new Date(summary.createdAt).toLocaleString()}

CATEGORY: ${summary.category}
DIFFICULTY: ${summary.difficulty}
READING TIME: ${summary.readingTime} minutes

--- SHORT SUMMARY ---
${summary.shortSummary}

--- DETAILED SUMMARY ---
${summary.detailedSummary}

--- KEY POINTS ---
${summary.keyPoints.map((p, idx) => `${idx + 1}. ${p}`).join("\n")}

--- ACTION ITEMS ---
${summary.actionItems.map((a, idx) => `[ ] ${a}`).join("\n")}

--- STUDY NOTES ---
${summary.studyNotes}

--- REVISION FLASHCARDS ---
${summary.flashcards.map((f, idx) => `Card ${idx + 1}:\nFront: ${f.front}\nBack: ${f.back}`).join("\n\n")}
`;
    downloadFile(textContent, `${summary.title.replace(/\s+/g, "_")}_summary.txt`, "text/plain");
  };

  const handleExportDocx = () => {
    // We export rich HTML which Microsoft Word opens, formats, and reads perfectly as a high-quality DOCX layout!
    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <title>${summary.title}</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333333; padding: 40px; }
          h1 { color: #4F46E5; border-bottom: 2px solid #4F46E5; padding-bottom: 10px; }
          h2 { color: #0C6BCE; margin-top: 30px; }
          ul { padding-left: 20px; }
          li { margin-bottom: 8px; }
          .meta { font-family: monospace; color: #666666; margin-bottom: 20px; }
          .card { background: #F3F4F6; border: 1px solid #E5E7EB; padding: 15px; border-radius: 8px; margin-bottom: 15px; }
          .section { margin-bottom: 40px; }
        </style>
      </head>
      <body>
        <h1>${summary.title}</h1>
        <div class="meta">
          <strong>Category:</strong> ${summary.category} | 
          <strong>Difficulty:</strong> ${summary.difficulty} | 
          <strong>Reading Time Saved:</strong> ${summary.readingTime}m
        </div>
        
        <div class="section">
          <h2>Concise Summary</h2>
          <p>${summary.shortSummary}</p>
        </div>

        <div class="section">
          <h2>Detailed Breakdown</h2>
          <div>${summary.detailedSummary.replace(/\n/g, "<br>")}</div>
        </div>

        <div class="section">
          <h2>Key Highlights</h2>
          <ul>
            ${summary.keyPoints.map((p) => `<li>${p}</li>`).join("")}
          </ul>
        </div>

        <div class="section">
          <h2>Action Items</h2>
          <ul>
            ${summary.actionItems.map((a) => `<li>[ ] ${a}</li>`).join("")}
          </ul>
        </div>

        <div class="section">
          <h2>Syllabus & Study Notes</h2>
          <p>${summary.studyNotes.replace(/\n/g, "<br>")}</p>
        </div>
      </body>
      </html>
    `;
    downloadFile(htmlContent, `${summary.title.replace(/\s+/g, "_")}_summary.docx`, "application/msword");
  };

  const handlePrint = () => {
    window.print();
  };

  const downloadFile = (content: string, filename: string, contentType: string) => {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-fade-in p-1">
      {/* Dynamic Print Preview Layout wrapper */}
      <style>
        {`
          @media print {
            body * {
              visibility: hidden;
            }
            #print-area, #print-area * {
              visibility: visible;
              color: black !important;
              background: white !important;
            }
            #print-area {
              position: absolute;
              left: 0;
              top: 0;
              width: 100%;
            }
            .no-print {
              display: none !important;
            }
          }
        `}
      </style>

      {/* Detail header menu toolbar */}
      <header className="flex flex-wrap items-center justify-between gap-4 no-print border-b border-outline-variant/10 pb-4">
        <button
          onClick={onBack}
          className="flex items-center gap-2 px-4 py-2 bg-surface-container/60 hover:bg-surface-variant/40 rounded-xl border border-outline-variant/20 transition-all text-sm font-semibold text-on-surface-variant cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Dashboard</span>
        </button>

        <div className="flex flex-wrap gap-2">
          {/* Favorites Star Bookmark Toggle */}
          <button
            onClick={(e) => onToggleBookmark(e, summary)}
            className="p-2 bg-surface-container/60 hover:bg-surface-variant/40 rounded-xl border border-outline-variant/20 transition-colors cursor-pointer"
            title="Toggle Bookmark"
          >
            <Star
              className={`w-5 h-5 ${
                summary.isBookmarked ? "text-secondary fill-secondary animate-pulse" : "text-on-surface-variant"
              }`}
            />
          </button>

          {/* Export Txt */}
          <button
            onClick={handleExportTxt}
            className="flex items-center gap-1.5 px-3 py-2 bg-surface-container/60 hover:bg-surface-variant/40 rounded-xl border border-outline-variant/20 text-xs font-semibold cursor-pointer"
            title="Export as Plain Text"
          >
            <Download className="w-4 h-4" />
            <span>TXT</span>
          </button>

          {/* Export Docx */}
          <button
            onClick={handleExportDocx}
            className="flex items-center gap-1.5 px-3 py-2 bg-surface-container/60 hover:bg-surface-variant/40 rounded-xl border border-outline-variant/20 text-xs font-semibold cursor-pointer"
            title="Export as Microsoft Word"
          >
            <Download className="w-4 h-4" />
            <span>DOCX</span>
          </button>

          {/* Print/PDF */}
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-2 bg-surface-container/60 hover:bg-surface-variant/40 rounded-xl border border-outline-variant/20 text-xs font-semibold cursor-pointer"
            title="Print Summary / Save PDF"
          >
            <Printer className="w-4 h-4" />
            <span>Print PDF</span>
          </button>

          {/* Delete Summary */}
          <button
            onClick={() => {
              if (confirm("Are you sure you want to permanently delete this AI summary?")) {
                onDelete(summary.summaryId);
              }
            }}
            className="px-3 py-2 bg-error-container/20 hover:bg-error-container/40 border border-error/20 rounded-xl text-error text-xs font-bold cursor-pointer"
          >
            Delete
          </button>
        </div>
      </header>

      {/* Main two-column presentation area */}
      <div id="print-area" className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        
        {/* Left Column: Interactive tabs panel workspace */}
        <div className="lg:col-span-8 space-y-6">
          
          {/* Note document titles display banner */}
          <div className="bg-gradient-to-tr from-surface-container-low/80 to-surface-container/40 p-6 rounded-2xl border border-outline-variant/15 space-y-2">
            <h1 className="text-2xl md:text-4xl font-extrabold tracking-tight text-on-surface">
              {summary.title}
            </h1>
            <p className="text-xs text-on-surface-variant font-medium uppercase font-mono flex items-center gap-2">
              <span>Category: <strong>{summary.category}</strong></span>
              <span>&bull;</span>
              <span>Level: <strong>{summary.difficulty}</strong></span>
              <span>&bull;</span>
              <span>Estimated: <strong>{summary.readingTime?.toFixed(0) || "2"} min read</strong></span>
            </p>
          </div>

          {/* Horizontal navigation tabs selector */}
          <div className="no-print flex overflow-x-auto gap-2 border-b border-outline-variant/15 pb-2 scrollbar-none">
            {[
              { id: "summary", label: "Summary", icon: FileText },
              { id: "keypoints", label: "Highlights", icon: Layers },
              { id: "actions", label: "Tasks", icon: CheckCircle },
              { id: "studynotes", label: "Study Kit", icon: Award },
              { id: "flashcards", label: "Flashcards", icon: Brain },
              { id: "quiz", label: "Quizzes", icon: BookOpen },
              { id: "mindmap", label: "Mind Map", icon: Sparkles },
            ].map((tab) => {
              const TabIcon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id as any)}
                  className={`flex items-center gap-1.5 px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider shrink-0 transition-all border cursor-pointer ${
                    activeTab === tab.id
                      ? "bg-secondary-container/10 border-secondary/50 text-secondary"
                      : "bg-surface-container/40 border-outline-variant/10 text-on-surface-variant hover:bg-surface-variant/20"
                  }`}
                >
                  <TabIcon className="w-3.8 h-3.8 shrink-0" />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>

          {/* Active Workspaces Content panels */}
          <div className="bg-surface-container/50 border border-outline-variant/15 rounded-2xl p-6 md:p-8 min-h-[350px]">
            
            {/* TAB: Summary */}
            {activeTab === "summary" && (
              <div className="space-y-6">
                <div className="no-print flex gap-2 border-b border-outline-variant/10 pb-3 justify-end">
                  <button
                    onClick={() => setSummaryLayout("short")}
                    className={`px-3 py-1.5 rounded-lg text-xs font-bold uppercase transition-all ${
                      summaryLayout === "short"
                        ? "bg-secondary text-on-secondary"
                        : "bg-surface-container-high text-on-surface-variant"
                    }`}
                  >
                    3-5 Sentence Brief
                  </button>
                  <button
                    onClick={() => setSummaryLayout("detailed")}
                    className={`px-3 py-1.5 rounded-lg text-xs font-bold uppercase transition-all ${
                      summaryLayout === "detailed"
                        ? "bg-secondary text-on-secondary"
                        : "bg-surface-container-high text-on-surface-variant"
                    }`}
                  >
                    Structured Breakdown
                  </button>
                </div>

                {summaryLayout === "short" ? (
                  <div className="space-y-4">
                    <h3 className="text-lg font-bold text-secondary flex items-center gap-1.5 border-b border-outline-variant/10 pb-2">
                      <Sparkles className="w-5 h-5" />
                      Executive Summary
                    </h3>
                    <p className="text-on-surface leading-8 text-base font-medium">
                      {summary.shortSummary}
                    </p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <h3 className="text-lg font-bold text-secondary border-b border-outline-variant/10 pb-2">
                      Detailed Document Breakdown
                    </h3>
                    {/* Render clean formatted paragraphs simulating markdown layout */}
                    <div className="text-on-surface leading-7 space-y-4 text-sm md:text-base">
                      {summary.detailedSummary?.split("\n\n").map((para, i) => {
                        if (para.trim().startsWith("#")) {
                          const cleanTitle = para.replace(/#/g, "").trim();
                          return <h4 key={i} className="text-lg font-bold text-primary mt-6">{cleanTitle}</h4>;
                        }
                        if (para.trim().startsWith("-") || para.trim().startsWith("*")) {
                          return (
                            <ul key={i} className="list-disc pl-5 space-y-2">
                              {para.split("\n").map((li, liIdx) => (
                                <li key={liIdx}>{li.replace(/^[\s-*\u2022]+/g, "")}</li>
                              ))}
                            </ul>
                          );
                        }
                        return <p key={i}>{para}</p>;
                      })}
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* TAB: Key highlights */}
            {activeTab === "keypoints" && (
              <div className="space-y-6">
                <h3 className="text-lg font-bold text-secondary border-b border-outline-variant/10 pb-2 flex items-center gap-2">
                  <Layers className="w-5 h-5 text-secondary" />
                  Key Points Extraction
                </h3>
                <ul className="space-y-4">
                  {summary.keyPoints.map((point, index) => (
                    <li
                      key={index}
                      className="flex gap-3 bg-surface-container-high/40 p-4 rounded-xl border border-outline-variant/10"
                    >
                      <span className="w-6 h-6 rounded-lg bg-secondary/10 border border-secondary/20 text-secondary flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                        {index + 1}
                      </span>
                      <p className="text-on-surface text-sm md:text-base">{point}</p>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* TAB: Action Checklist */}
            {activeTab === "actions" && (
              <div className="space-y-6">
                <h3 className="text-lg font-bold text-secondary border-b border-outline-variant/10 pb-2 flex items-center gap-1.5">
                  <CheckCircle className="w-5 h-5" />
                  Action Items Detection
                </h3>
                {summary.actionItems.length === 0 ? (
                  <p className="text-on-surface-variant text-sm py-4">
                    No urgent tasks, milestones, or assignments were identified in this document.
                  </p>
                ) : (
                  <div className="space-y-3">
                    {summary.actionItems.map((action, idx) => (
                      <div
                        key={idx}
                        onClick={() => toggleActionItem(idx)}
                        className={`flex gap-3 p-4 rounded-xl border cursor-pointer select-none transition-all ${
                          checkedActionItems[idx]
                            ? "bg-emerald-950/10 border-emerald-500/20 text-on-surface-variant"
                            : "bg-surface-container-low hover:bg-surface-variant/30 border-outline-variant/10 text-on-surface"
                        }`}
                      >
                        <div
                          className={`w-5 h-5 rounded border shrink-0 flex items-center justify-center transition-all mt-0.5 ${
                            checkedActionItems[idx]
                              ? "bg-emerald-500 border-emerald-400 text-on-primary"
                              : "border-outline-variant hover:border-secondary"
                          }`}
                        >
                          {checkedActionItems[idx] && <CheckCircle className="w-4 h-4 text-emerald-950" />}
                        </div>
                        <span className={`text-sm md:text-base ${checkedActionItems[idx] ? "line-through opacity-55" : ""}`}>
                          {action}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* TAB: Study Kit & ELI5 */}
            {activeTab === "studynotes" && (
              <div className="space-y-8">
                <div className="space-y-4">
                  <h3 className="text-lg font-bold text-secondary border-b border-outline-variant/10 pb-2">
                    Syllabus Exam Prep Notes
                  </h3>
                  <div className="text-on-surface leading-7 space-y-4 text-sm md:text-base bg-surface-container-lowest/30 p-6 rounded-xl border border-outline-variant/10">
                    {summary.studyNotes?.split("\n\n").map((section, idx) => {
                      if (section.trim().startsWith("#")) {
                        const word = section.replace(/#/g, "").trim();
                        return <h4 key={idx} className="text-lg font-bold text-primary pt-3">{word}</h4>;
                      }
                      return <p key={idx}>{section}</p>;
                    })}
                  </div>
                </div>

                {summary.explainLikeIm5 && (
                  <div className="space-y-3 bg-primary-container/10 border border-primary/20 p-6 rounded-2xl">
                    <h3 className="text-base font-bold text-primary flex items-center gap-1.5 uppercase font-mono tracking-wider">
                      <Flame className="w-5 h-5 text-secondary fill-secondary" />
                      Explain Like I'm 5 (Analogy Mode)
                    </h3>
                    <p className="text-on-surface text-sm md:text-base leading-relaxed italic">
                      "{summary.explainLikeIm5}"
                    </p>
                  </div>
                )}
              </div>
            )}

            {/* TAB: Revision Flashcards */}
            {activeTab === "flashcards" && (
              <div className="space-y-6">
                <h3 className="text-lg font-bold text-secondary border-b border-outline-variant/10 pb-2">
                  Revision Flashcards
                </h3>
                <p className="text-xs text-on-surface-variant">
                  Click on any flashcard below to execute 3D Flip actively recall definitions...
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {summary.flashcards.map((card, idx) => (
                    <div
                      key={idx}
                      onClick={() => flipFlashcard(idx)}
                      className="min-h-[160px] cursor-pointer relative perspective"
                    >
                      {/* Innermost card */}
                      <div
                        className={`w-full h-full rounded-2xl border p-6 flex flex-col items-center justify-center text-center transition-transform duration-500 absolute preserve-3d ${
                          clickedFlashcards[idx]
                            ? "bg-secondary-container/10 border-secondary/40 rotate-x-180"
                            : "bg-surface-container-high border-outline-variant/20 hover:border-secondary/20"
                        }`}
                      >
                        {!clickedFlashcards[idx] ? (
                          <div className="space-y-3">
                            <span className="text-[10px] bg-secondary/15 uppercase font-bold text-secondary px-2.5 py-1 rounded-full font-mono">
                              FRONT
                            </span>
                            <h4 className="text-base font-bold text-on-surface leading-snug">
                              {card.front}
                            </h4>
                          </div>
                        ) : (
                          <div className="space-y-3 transform rotate-x-180">
                            <span className="text-[10px] bg-primary/15 uppercase font-bold text-primary px-2.5 py-1 rounded-full font-mono">
                              BACK
                            </span>
                            <p className="text-sm font-medium text-on-surface leading-relaxed">
                              {card.back}
                            </p>
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* TAB: Interactive Quiz MCQs */}
            {activeTab === "quiz" && (
              <div className="space-y-8">
                <h3 className="text-lg font-bold text-secondary border-b border-outline-variant/10 pb-2">
                  Knowledge Evaluation Quizzes
                </h3>

                <div className="space-y-6">
                  {summary.questions.map((q, qIndex) => (
                    <div
                      key={qIndex}
                      className="bg-surface-container-lowest/60 p-5 rounded-2xl border border-outline-variant/15 space-y-4"
                    >
                      <div className="flex gap-2 items-start">
                        <span className="text-xs font-mono font-bold text-primary mt-1">Q{qIndex + 1}.</span>
                        <h4 className="text-base font-bold">{q.question}</h4>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                        {q.options.map((opt, optIndex) => {
                          const isSelected = quizAnswers[qIndex] === optIndex;
                          const isCorrectOpt = optIndex === q.answerIndex;
                          const wasSubmitted = quizSubmitted[qIndex];

                          let btnStyle = "bg-surface-container-low hover:bg-surface-variant/40 border-outline-variant/10";
                          if (wasSubmitted) {
                            if (isCorrectOpt) {
                              btnStyle = "bg-emerald-950/20 border-emerald-500/50 text-emerald-400";
                            } else if (isSelected) {
                              btnStyle = "bg-error-container/20 border-error/50 text-error";
                            } else {
                              btnStyle = "bg-surface-container-low border-outline-variant/10 opacity-45";
                            }
                          }

                          return (
                            <button
                              key={optIndex}
                              type="button"
                              onClick={() => handleSelectOption(qIndex, optIndex)}
                              className={`w-full p-3.5 rounded-xl border text-left text-sm font-semibold transition-all cursor-pointer ${btnStyle}`}
                            >
                              <div className="flex justify-between items-center">
                                <span>{opt}</span>
                                {wasSubmitted && isCorrectOpt && (
                                  <span className="text-[10px] uppercase tracking-wider font-bold text-emerald-400">
                                    Correct
                                  </span>
                                )} 
                              </div>
                            </button>
                          );
                        })}
                      </div>

                      {quizSubmitted[qIndex] && (
                        <div className="bg-surface-container/50 p-4 rounded-xl text-xs space-y-1.5 border border-outline-variant/10 leading-relaxed text-on-surface-variant font-medium">
                          <p className="font-bold uppercase font-mono tracking-wider text-secondary">
                            RATIONALE EXPLANATION:
                          </p>
                          <p>"{q.explanation}"</p>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* TAB: Hierarchical SVG Mind Map */}
            {activeTab === "mindmap" && (
              <div className="space-y-6">
                <h3 className="text-lg font-bold text-secondary border-b border-outline-variant/10 pb-2">
                  Hierarchical Topic Mind Map
                </h3>
                <p className="text-xs text-on-surface-variant">
                  Interactive conceptual hierarchy trees parsed from the document structure:
                </p>

                {/* Nested Mindmap diagram visualization */}
                <div className="bg-surface-container-lowest/80 p-6 rounded-2xl border border-outline-variant/10 relative overflow-hidden space-y-4">
                  {/* Root Topic */}
                  <div className="flex justify-center">
                    <div className="bg-gradient-to-r from-primary to-secondary p-4.5 rounded-xl shadow-lg shadow-primary/10 text-on-primary font-bold text-sm tracking-wide text-center uppercase min-w-[200px]">
                      {summary.mindMap?.name || summary.title}
                    </div>
                  </div>

                  {/* Branches connectors lines simulated in visual layout */}
                  <div className="space-y-4 pt-4">
                    {summary.mindMap?.children?.map((child, cIdx) => (
                      <div
                        key={cIdx}
                        className="bg-surface-container-low/80 p-4.5 rounded-xl border border-outline-variant/15 flex flex-col md:flex-row md:items-center justify-between gap-4"
                      >
                        <div className="flex items-center gap-2">
                          <ChevronRight className="w-4 h-4 text-secondary shrink-0" />
                          <h4 className="font-bold text-sm text-secondary uppercase tracking-wider font-sans">
                            {child.name}
                          </h4>
                        </div>

                        {/* Leaves */}
                        <div className="flex flex-wrap gap-2">
                          {child.children?.map((leaf, lIdx) => (
                            <span
                              key={lIdx}
                              className="px-3 py-1.5 bg-surface-container-high/60 border border-outline-variant/20 rounded-lg text-xs font-semibold text-on-surface-variant"
                            >
                              {leaf.name}
                            </span>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right Column: Metadata details side rail */}
        <aside className="lg:col-span-4 space-y-6 no-print">
          
          {/* Metadata properties box */}
          <section className="bg-surface-container/60 backdrop-blur-md border border-outline-variant/15 p-6 rounded-2xl space-y-6">
            <h3 className="text-sm font-bold text-secondary uppercase font-mono tracking-widest border-b border-outline-variant/10 pb-2">
              Note Insights
            </h3>

            {/* Category / Sentiment / Difficulty */}
            <div className="space-y-4">
              <div className="flex justify-between items-center text-sm border-b border-outline-variant/5 pb-2">
                <span className="text-on-surface-variant text-xs">Topic Classification:</span>
                <span className="font-bold text-on-surface font-sans uppercase">{summary.category}</span>
              </div>
              
              <div className="flex justify-between items-center text-sm border-b border-outline-variant/5 pb-2">
                <span className="text-on-surface-variant text-xs">Content Sentiment:</span>
                <span className="font-bold text-on-surface uppercase">{summary.sentiment}</span>
              </div>

              <div className="flex justify-between items-center text-sm border-b border-outline-variant/5 pb-2">
                <span className="text-on-surface-variant text-xs">Difficulty Detection:</span>
                <span className="px-2.5 py-0.5 rounded-full font-bold uppercase text-[10px] bg-secondary/15 border border-secondary/30 text-secondary">
                  {summary.difficulty}
                </span>
              </div>
            </div>

            {/* Keyword tags */}
            <div className="space-y-2">
              <span className="text-on-surface-variant text-xs font-semibold uppercase font-mono tracking-wider">
                Extracted Keywords:
              </span>
              <div className="flex flex-wrap gap-1.5">
                {summary.keywords.map((word, i) => (
                  <span
                    key={i}
                    className="px-2.5 py-1 bg-surface-container-high border border-outline-variant/15 rounded-lg text-xs font-semibold text-on-surface-variant"
                  >
                    #{word}
                  </span>
                ))}
              </div>
            </div>
          </section>

          {/* Important dates and metrics sidebox */}
          {summary.importantDatesNumbersFullList && summary.importantDatesNumbersFullList.length > 0 && (
            <section className="bg-surface-container/60 backdrop-blur-md border border-outline-variant/15 p-6 rounded-2xl space-y-4">
              <h3 className="text-sm font-bold text-secondary uppercase font-mono tracking-widest border-b border-outline-variant/10 pb-2 flex items-center gap-1.5">
                <Calendar className="w-4 h-4" />
                DATES & NUMBERS
              </h3>
              <ul className="space-y-2 max-h-[250px] overflow-y-auto pr-1">
                {summary.importantDatesNumbersFullList.map((item, idx) => (
                  <li
                    key={idx}
                    className="text-xs font-medium leading-relaxed bg-surface-container-low border border-outline-variant/10 p-2.5 rounded-lg text-on-surface-variant"
                  >
                    {item}
                  </li>
                ))}
              </ul>
            </section>
          )}

          {/* File original text viewer sidebar */}
          <section className="bg-surface-container/30 border border-outline-variant/15 p-6 rounded-2xl space-y-3">
            <h4 className="text-sm font-bold">Source Content Length</h4>
            <div className="grid grid-cols-2 gap-2 text-center font-mono text-xs">
              <div className="bg-surface-container-low p-3 rounded-xl border border-outline-variant/5">
                <p className="text-[10px] text-on-surface-variant font-sans uppercase">Words</p>
                <p className="text-lg font-bold text-on-surface">{summary.wordCount || "0"}</p>
              </div>
              <div className="bg-surface-container-low p-3 rounded-xl border border-outline-variant/5">
                <p className="text-[10px] text-on-surface-variant font-sans uppercase">Characters</p>
                <p className="text-lg font-bold text-on-surface">{summary.charCount || "0"}</p>
              </div>
            </div>
          </section>
        </aside>
      </div>
    </div>
  );
}
